---
development:
  dialect: postgres
  database: social_api_development
  user: postgres_user
  password: postgres
  host: 192.168.86.40
  port: 4321
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres_user:postgres@192.168.86.40:4321/social_api_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres_user:postgres@192.168.86.40:4321/social_api_production?sslmode=disable"}}
