package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"social_api/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Feed)
// DB Table: Plural (feeds)
// Resource: Plural (Feeds)
// Path: Plural (/feeds)
// View Template Folder: Plural (/templates/feeds/)

// FeedsResource is the resource for the Feed model
type FeedsResource struct {
	buffalo.Resource
}

// List gets all Feeds. This function is mapped to the path
// GET /feeds
func (v FeedsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	feeds := &models.Feeds{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Feeds from the DB
	if err := q.All(feeds); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("feeds", feeds)
		return c.Render(http.StatusOK, r.HTML("feeds/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(feeds))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(feeds))
	}).Respond(c)
}

// Show gets the data for one Feed. This function is mapped to
// the path GET /feeds/{feed_id}
func (v FeedsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Feed
	feed := &models.Feed{}

	// To find the Feed the parameter feed_id is used.
	if err := tx.Find(feed, c.Param("feed_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("feed", feed)

		return c.Render(http.StatusOK, r.HTML("feeds/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(feed))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(feed))
	}).Respond(c)
}

// Create adds a Feed to the DB. This function is mapped to the
// path POST /feeds
func (v FeedsResource) Create(c buffalo.Context) error {
	// Allocate an empty Feed
	feed := &models.Feed{}

	// Bind feed to the html form elements
	if err := c.Bind(feed); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(feed)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("feed", feed)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("feeds/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "feed.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/feeds/%v", feed.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(feed))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(feed))
	}).Respond(c)
}

// Update changes a Feed in the DB. This function is mapped to
// the path PUT /feeds/{feed_id}
func (v FeedsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Feed
	feed := &models.Feed{}

	if err := tx.Find(feed, c.Param("feed_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Feed to the html form elements
	if err := c.Bind(feed); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(feed)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("feed", feed)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("feeds/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "feed.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/feeds/%v", feed.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(feed))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(feed))
	}).Respond(c)
}

// Destroy deletes a Feed from the DB. This function is mapped
// to the path DELETE /feeds/{feed_id}
func (v FeedsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Feed
	feed := &models.Feed{}

	// To find the Feed the parameter feed_id is used.
	if err := tx.Find(feed, c.Param("feed_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(feed); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "feed.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/feeds")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(feed))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(feed))
	}).Respond(c)
}
